# Generated by Django 5.0.1 on 2024-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=300, null=True),
        ),
    ]
